# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-24.04 # ubuntu-latest tag has been deprecated. See https://github.com/actions/runner-images/issues/10636
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
        
    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies for requests in Python 3.9
      # it's not clear why this is needed only for this version of python
      if: matrix.python-version == 3.9
      run: sudo apt-get install libxml2-dev libxslt-dev

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv and set Python version
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.8"
        python-version: ${{ matrix.python-version }}
      
    - name: Install dependencies
      run: |
        uv sync --locked --dev --all-extras

    - name: Check type annotations
      run: |
        uv run pyright

    - name: Check codebase
      run: |
        uv run ruff check

    - name: Check formatting
      run: |
        uv run ruff format --check

    - name: Test with pytest
      # Wrapped by coverage to generate coverage data
      run: |
        uv run coverage run --omit="tests*" -m pytest

    - name: Generate coverage report
      run: |
        uv run coverage report
